### ISSUE TITLE
Question: Using an update call?

### ISSUE THREAD

**Issue by webbo89** [mostr/angular-ui-multi-sortable#1]
Thanks so much for making this repo, the most elegant solution I have seen.

Do you have any advice on the best way to initiate an update event or similar?

My app doesn't require any sophisticated calls, I'd simply like to call a function inside the $scope of my module to notify my code the lists have been moved.

I've turned your demo into a jsfiddle, and created a function $scope.changed to help explain.

http://jsfiddle.net/webbo89/xJAPc/3/

Many thanks!

**Comment by mostr** [comment]
Hi Jonathan, I'm glad you find this repo useful. 

Regarding this issue I've created new branch with a change here https://github.com/mostr/angular-ui-multi-sortable/tree/improve_user_callbacks and updated your jsfiddle to work with this new implementation http://jsfiddle.net/xJAPc/4/ 
Please note you can invoke both angular $scope functions (defined as function names as shown in "update" callback) and also "standalone" functions as well, as shown in "stop" and "start" params.

Let me know if this is what you asked for. If so I'll merge that into master.

**Comment by webbo89** [comment]
It is indeed!

That is fantastic - thanks again - very helpful!
