### ISSUE TITLE
Causes Undefined error from mouse up event in jquery-ui.js

### ISSUE THREAD

**Issue by garymazz** [mostr/angular-ui-multi-sortable#14]
TypeError: $parse(...)(...) is undefined
_mouseUp()jquery-ui.js (line 958)
event = Object { originalEvent=Event mouseup, type="mouseup", timeStamp=296384489, more...}
_superApply()jquery-ui.js (line 401)
_mouseUpDelegate()jquery-ui.js (line 914)
event = Object { originalEvent=Event mouseup, type="mouseup", timeStamp=296384489, more...}
removeData()jquery....min.js (line 3)
a = Object { originalEvent=Event mouseup, type="mouseup", timeStamp=296384489, more...}
(?)()angular.min.js (line 3)
b = mouseup clientX=111, clientY=512

this._mouseStop(event);

The library stack:
        script src="libs/jquery/jquery-2.1.0.min.js"></script>
        script src="libs/jquery/jquery-ui-1.10.4/ui/jquery-ui.js" type="text/javascript"></script>  
        script src="libs/angularjs/angular-1.2.7/angular.min.js" type="text/javascript"></script> 
        script src="libs/angularjs/angular-1.2.7/angular-route.min.js" type="text/javascript"></script>
        script src="libs/angularjs/angular-1.2.7/angular-resource.min.js" type="text/javascript"></script>
        script src="libs/angularjs/ui/ui-bootstrap-tpls-0.10.0.min.js" type="text/javascript"></script>
        script src="libs/angularjs/adapters/sortable.js" type="text/javascript"></script> 
        script src="libs/angularjs/adapters/multiSortable.js" type="text/javascript"></script>

**Comment by mostr** [comment]
Hey, I see you use angular 1.2.x and jquery 2.x. I'm afraid it will not work with your setup. Please take a look at https://github.com/angular-ui/ui-sortable. They more or less mirrored what my "thing" provides but their thing work with newer versions of Angular and jQuery.
