### ISSUE TITLE
Introduce versioning

### ISSUE THREAD

**Issue by alari** [mostr/angular-ui-multi-sortable#4]
Hi there.

I'm happy to depend on your code, it works great and perfectly fit my needs, thank you!

But to maintain my dependencies I want to ask you to introduce some kind of versioning policy, so that it would be easy to understand what is fresher and what is not.

A simple `@version` in the header will be enough :)

Thanks :)

**Comment by mostr** [comment]
I've added Bower's `component.json` and this component is available in Bower's repository under `angular-ui-multi-sortable`. It should be more than enough for your needs.
