### ISSUE TITLE
Cannot run version 0.0.2 in firefox, ie

### ISSUE THREAD

**Issue by hbt272** [mostr/angular-ui-multi-sortable#6]
hi mostr,
I'd like to use version 0.0.2 with sortable directive and selectable directive to create a list can multi select and multi sort.
But it work fine in chrome, opera. Can not work in firefox and ie.
It throw error: "Error: cannot call methods on sortable prior to initialization; attempted to call method 'option'"
The error at line #114: iElement.sortable('option', 'helper', helper);
Can you show me why it can work in Chrome but not in Firefox?
Do you have any solutions for this issue?

Thank you very much!

**Comment by mostr** [comment]
Weird. I've just checked it in Firefox 23.0.1 and it works perfectly fine. Could you please add more details to this issue if it still persists?

**Comment by hbt272** [comment]
I have custom your demo at selectable.html 
https://docs.google.com/file/d/0B2HqMNENKcYKNWZvV2JWb2IwT1U/edit?usp=sharing
And my firefox version is 23.0.1 too. It also not working on IE 10.
Please help!

![sort](https://f.cloud.github.com/assets/1578958/1133067/a7e8aa20-1bd6-11e3-915d-bdcd5edfd496.png)

**Comment by hbt272** [comment]
Hi mostr,
I see this problem. 
Firefox parse the DOM difference with Chrome DOM.
How to solve this problem?

# see my captures:

CASE 1: I place 'uis-sortable' before 'uis-selectable' -> chrome OK, firefox ERROR
![before](https://f.cloud.github.com/assets/1578958/1135895/2625173c-1c29-11e3-8c09-e143ca588d95.png)

# 

CASE 2: I switch them positions -> Chome ERROR, firefox OK
![after](https://f.cloud.github.com/assets/1578958/1135897/2d125348-1c29-11e3-80a3-e3ef06679151.png)
